name: NotifCraft
options:
  bundleIdPrefix: com.vincentdeby
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

targets:
  NotifCraft:
    type: application
    platform: iOS
    sources:
      - Sources
    resources:
      - Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vincentdeby.notifcraft
        SWIFT_VERSION: "5.0"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: "1,2"
        INFOPLIST_KEY_UILaunchScreen_Generation: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: "NotifCraft"
        UIRequiredDeviceCapabilities: [armv7]
